name: One_Piece
version: 1.0.15
main: com.example.banitem.BanItemSaver
api-version: 1.21
authors: [ManakaGekka]
description: Saves banned players' items in a barrel.
broadcast-message: "被封禁玩家 {player} 的物品已保存，位置：{coords}"
encrypt-coordinates: true
commands:
  reload:
    description: Reloads the plugin configuration
    usage: /reload
    permission: one_piece.reload
    permission-message: 你没有权限使用此命令。